#:schema node_modules/wrangler/config-schema.json

name = "doggo-elm"
pages_build_output_dir = "./dist"
compatibility_date = "2024-09-03"

# NOTE: this part taken from rust worker config (may help)
# Custom domains - forward everything to domain.
# https://developers.cloudflare.com/workers/configuration/routing/custom-domains/
# Path-based routing: https://developers.cloudflare.com/workers/wrangler/configuration/#routes
# route = { pattern = "doggo.lab.kulagin.dev", custom_domain = true }

[dev]
port = 8989
local_protocol = "http"
