#:schema node_modules/wrangler/config-schema.json

# Conf docs: https://developers.cloudflare.com/workers/wrangler/configuration/
# Crate docs: https://github.com/cloudflare/workers-rs

name = "doggo-elm"
pages_build_output_dir = "./dist"
compatibility_date = "2024-09-03"

# Custom domains - forward everything to domain.
# https://developers.cloudflare.com/workers/configuration/routing/custom-domains/
# Path-based routing: https://developers.cloudflare.com/workers/wrangler/configuration/#routes

#route = { pattern = "nps-rs.kulagin.dev", custom_domain = true }

[dev]
port = 8989
local_protocol = "http"
